spring:
  datasource:
    url: jdbc:mysql://43.142.151.181:3306/river?useSSL=false&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Dream1226.27!

  redis:
    host: 43.142.151.181
    port: 6399
    database: 0
    password:
    max-idle: 8
    max-active: 16
    max-wait: -1
    min-idle: 0
    timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://124.222.217.230:8001/eureka/


# 配置ftp服务器信息
ftp:
  # ftp服务器的IP地址
  url: 47.105.148.90
  # 默认端口是21
  port: 21
  username: sxl14459048
  password: APdSNYEy5AakCSiG
  # ftp服务器存放文件的路径
  remotePath: /data/ftp
  # 本地需要上传的文件的路径
  localDir: /Users/coatardbul/Desktop
  # ftp上文件下载到本地存放的路径
  downDir: /Users/coatardbul/Desktop